# Generated by Django 2.2.1 on 2019-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
